### PR TITLE
Hope it fulfills the issue!!

### PR DESCRIPTION
**Pull request by gauravbisht005**
Hope this is what you wanted!!
Else let me know... I'll ammend.

### CODE REVIEW

**Comment by csviri** [comment]
Hi @gauravbisht005 thank you for PR.

One remark, do we really need html for this? 
See second answer here: https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown

would be nice to have it as pure markdown

**Comment by gauravbisht005** [comment]
> Hi @gauravbisht005 thank you for PR.
> 
> One remark, do we really need html for this?
> See second answer here: https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown
> 
> would be nice to have it as pure markdown

Okay!! Thank you for the feedback. I'll make the changes by the evening(IST 2000Hrs)

**Comment by gauravbisht005** [comment]
I've made the amendments as stated! 
Thank you :)

**Review by csviri — APPROVED** [review]
LGTM, yep great thx!!

**Pull request merged**
