### PR TITLE
fix: type UpdateControl with the interface's parameter type

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by adam-sandor** [comment]
thanks for the PR @metacosm ! consider jumping into our discord for a chat about what you think of the project https://discord.gg/SvNGTU

**Comment by amouat** [comment]
Hi @metacosm,

This PR falls under our Hacktoberfest promotion: https://blog.container-solutions.com/container-solutions-does-hacktoberfest

If you'd like a t-shirt, please send me (adrian.mouat@container-solutions.com) an e-mail with your size and mailing address.

Thanks for the PR!

**Comment by metacosm** [comment]
Hi @amouat,

I don't think I've really earned it… 😉

**Comment by amouat** [comment]
It's certainly borderline! I'm happy to send out a shirt if you'd like though.

**Comment by metacosm** [comment]
> It's certainly borderline! I'm happy to send out a shirt if you'd like though.

While I'd like a shirt, I don't need it and I'd feel conflicted about the associated cost both monetary and environmental for so little a contribution… Thank you anyway, that was unexpected. 😄

**Comment by amouat** [comment]
Next year I'm hoping we'll copy DO's lead and have the option to plant a tree instead.

**Comment by metacosm** [comment]
That would be neat, indeed, though I'm a little dubious about the long term efficacy of tree planting i.e. the tree needs to actually survive… sponsoring existing forests/restoring hedges to preserve biodiversity might be a better play… as usual the devil's is the details and planting a tree is certainly better than not planting one! Thanks for considering this option!

**Pull request merged**
